version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3000}"
    environment:
      - PORT=3000
      - SECRET_AUTH_KEY=${SECRET_AUTH_KEY}
      - APP_MODE=${APP_MODE}
      - HIDE_POST_ENDPOINTS=${HIDE_POST_ENDPOINTS}
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - db_postgres
    restart: always

  volumes:
    postgres-data:


  networks:
    db_postgres:
      external: true
